/**
 * Compras desde /compras/PDF (Julio 2026).
 * DEFA: PAEA15795 + ajuste +$4.000 + PAEA15948 (14-jul).
 * Tubo EMT/IMC: barra estandar de 3 m.
 */
const COMPRAS_IMPORT = {
  version: "compras-v10",
  notes: [
    "PDF Solar Hub CTSHCAR260235: $39.002.846 (51 paneles, inversores, estructura Alurack, MC4, dongle).",
    "PDF DEFA PAEA15795: $2.954.424,77 + $4.000 ajuste conduleta = $2.958.424,77.",
    "PDF Devolucion conduleta PAEA15807: se devolvio EMT 1 T y se compro EMT 1 LR; neto +$4.000 a DEFA.",
    "PDF DEFA PAEA15948 (14-jul): $2.934.370,62 (cable #2 110 m, conector coraza 1\", grapa 3/4\").",
    "PDF Soluciones Electricas N3598: $400.000 (comprado por Gustavo A.).",
    "PDF Casa Dielectrica FEA5-32889: $75.000 (2 cajas 12P, comprado por Gustavo A.).",
    "PDF INELDEC C-1-10482 (16-jul): $3.933.000 (breakers DC, cable PV 6mm, DPS DC/AC).",
    "PDF Casa Electrica FE1-277774 (14-jul): $5.200 — grapa tensora T-2 (Gustavo A.).",
    "PDF Casa Electrica FE1-277678 (14-jul): $200.400 — coraza, conectores EMT-coraza, anclas (Gustavo A.).",
    "PDF Todo Tornillo FETT 00289611 (15-jul): $22.525 — arandelas, chazos, tornilleria (Gustavo A.).",
    "Comprador por defecto: Dr Tabares. Gustavo A.: N3598, FEA5-32889, FE1-277774, FE1-277678, FETT 00289611.",
    "Totales de factura en UI usan valor PDF (con IVA cuando aplica). Renglones DEFA/INELDEC van a subtotal.",
  ],
  retireItemIds: [
    "shared-pago-bancolombia",
    "shared-defa-pagina2-pendiente",
    "shared-pago-dist-electricas",
  ],
  supersedeInvoiceIds: [
    "inv-defa-emt-8kw",
    "inv-defa-emt-20kw",
    "inv-defa-imc-8kw",
    "inv-defa-union-imc",
    "inv-defa-curva-emt",
    "inv-defa-curva-imc",
    "inv-defa-term-emt",
    "inv-defa-union-emt",
    "inv-defa-boquilla",
    "inv-defa-cinta-n",
    "inv-defa-cinta-b",
    "inv-defa-cinta-r",
    "inv-defa-pagina2",
    "inv-sep-caja8",
    "inv-sep-caja6",
    "inv-sep-breaker-base",
    "inv-sep-breaker-extra",
    "inv-sep-amarras",
    "inv-sep-totalizador",
    "inv-sep-barra",
    "inv-sep-pin",
    "inv-cd-caja12",
    "inv-dist-ac",
    "inv-bancolombia",
  ],
  newItems: [
    {
      id: "20kW-extra-totalizador-100A",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Totalizador bifasico 100 A (acometida / tablero principal)",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 160000,
      notas: "Soluciones Electricas Pasto N3598",
    },
    {
      id: "20kW-extra-caja-8p",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Caja de distribucion sobreponer con tapa 8P",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 35000,
      notas: "Soluciones Electricas Pasto N3598",
    },
    {
      id: "8kW-extra-caja-6p",
      project: "8kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Caja de distribucion sobreponer con tapa 6P",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 26000,
      notas: "Soluciones Electricas Pasto N3598",
    },
    {
      id: "20kW-extra-caja-12p",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Caja plastica con tapa 12P (Voltio) para protecciones",
      unidad: "und",
      cantidadProyectada: 2,
      precioPromedioInternet: 37500,
      notas: "Casa Dielectrica FEA5-32889",
    },
    {
      id: "20kW-extra-breaker-63A",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Minibreaker Schneider 2P 63 A (respaldo / salida adicional)",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 50000,
      notas: "Tercera unidad — Soluciones Electricas N3598",
    },
    {
      id: "shared-extra-amarras",
      project: "8kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Paquete de amarras plasticas",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 11000,
      notas: "Soluciones Electricas N3598",
    },
    {
      id: "shared-extra-terminal-barra",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Terminal / barra 2 bornes (tern x 2 BYT)",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 3000,
      notas: "Soluciones Electricas N3598 — 4 und x $3.000",
    },
    {
      id: "shared-extra-terminal-pin",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Terminal pin hueco #6 verde",
      unidad: "und",
      cantidadProyectada: 12,
      precioPromedioInternet: 500,
      notas: "Soluciones Electricas N3598",
    },
    {
      id: "shared-extra-union-imc-34",
      project: "8kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Union galvanizada / IMC 3/4\"",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 944,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-curva-emt-1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Curva EMT 1\"",
      unidad: "und",
      cantidadProyectada: 5,
      precioPromedioInternet: 1981,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-curva-imc-34",
      project: "8kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Curva galvanizada / IMC 3/4\"",
      unidad: "und",
      cantidadProyectada: 6,
      precioPromedioInternet: 3255,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-terminal-emt-1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Terminal EMT 1\" acero",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 1261,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-union-emt-1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Union EMT 1\" acero",
      unidad: "und",
      cantidadProyectada: 6,
      precioPromedioInternet: 947,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-boquilla-34",
      project: "8kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Juego de boquilla y contratuerca 3/4\"",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 758,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-cinta-negra",
      project: "8kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Cinta aislante negra economica x 18 m",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 2269,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-cinta-blanca",
      project: "8kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Cinta aislante blanca",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 2297,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-cinta-roja",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Cinta aislante Temflex roja grande",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 4790,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-cinta-verde",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Cinta aislante Temflex verde grande",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 4790,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-conduleta-emt1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Conduleta EMT 1\" LR (recompra tras devolucion T)",
      unidad: "und",
      cantidadProyectada: 2,
      precioPromedioInternet: 12826,
      notas: "DEFA PAEA15807 — ajuste neto +$4.000 sobre PAEA15795",
    },
    {
      id: "shared-extra-caja-rawelt",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Caja tipo Rawelt 2400 3 salidas 3/4\"",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 16376,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-grapa-emt1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Grapa doble oreja Galv/EMT 1\" C20",
      unidad: "und",
      cantidadProyectada: 12,
      precioPromedioInternet: 236,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-conector-coraza-1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Conector recto 1\" coraza",
      unidad: "und",
      cantidadProyectada: 37,
      precioPromedioInternet: 4419,
      notas: "DEFA PAEA15948 (17) + Casa Electrica FE1-277678 (20)",
    },
    {
      id: "shared-extra-grapa-imc-34",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Grapa doble oreja 3/4\" Galv para IMC/EMT",
      unidad: "und",
      cantidadProyectada: 5,
      precioPromedioInternet: 197,
      notas: "DEFA PAEA15948",
    },
    {
      id: "8kW-extra-seccionador-dc-20A",
      project: "8kW",
      section: "3. CIRCUITO DC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Breaker/seccionador DC riel 2x20A 1000V Suntree",
      unidad: "und",
      cantidadProyectada: 2,
      precioPromedioInternet: 149580,
      notas: "INELDEC C-1-10482",
    },
    {
      id: "shared-extra-tensor-antifraude",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Tensor antifraude monofasico",
      unidad: "und",
      cantidadProyectada: 2,
      precioPromedioInternet: 2052,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-grapa-tensora-t2",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Grapa tensora para acometida T-2",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 5200,
      notas: "Casa Electrica FE1-277774 · Gustavo A.",
    },
    {
      id: "shared-extra-coraza-1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Coraza metal protegida 1\"",
      unidad: "ml",
      cantidadProyectada: 4,
      precioPromedioInternet: 10300,
      notas: "Casa Electrica FE1-277678 · Gustavo A.",
    },
    {
      id: "shared-extra-disco-corte-metal",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Disco corte metal 4-1/2\"",
      unidad: "und",
      cantidadProyectada: 2,
      precioPromedioInternet: 2000,
      notas: "Casa Electrica FE1-277678 · Gustavo A.",
    },
    {
      id: "shared-extra-ancla-hlc-516",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Ancla HLC 5/16 x 1-1/2",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 500,
      notas: "Casa Electrica FE1-277678 · Gustavo A.",
    },
    {
      id: "shared-extra-broca-muro-516",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Broca para muro 5/16 x 4",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 3000,
      notas: "Casa Electrica FE1-277678 · Gustavo A.",
    },
    {
      id: "shared-extra-ferreteria-todo-tornillo",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Techo solar",
      descripcion: "Ferreteria montaje (arandelas, chazos, tornillos) Todo Tornillo",
      unidad: "global",
      cantidadProyectada: 1,
      precioPromedioInternet: 22525,
      notas: "Todo Tornillo FETT 00289611 · Gustavo A. · desglose en factura",
    },
    {
      id: "shared-extra-bolsa-manigueta",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Bolsa manigueta biodegradable",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 200,
      notas: "Casa Electrica FE1-277678 · Gustavo A.",
    },
    {
      id: "shared-extra-dongle-huawei",
      project: "20kW",
      section: "1. GENERACIÓN FOTOVOLTAICA",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Dongle Huawei SDONGLEA-05 (02312QMV)",
      unidad: "und",
      cantidadProyectada: 2,
      precioPromedioInternet: 249900,
      notas: "Solar Hub CTSHCAR260235",
    },
    {
      id: "shared-extra-union-perfil-alurack",
      project: "20kW",
      section: "2. ESTRUCTURA DE MONTAJE",
      seccionOperativa: "Techo solar",
      descripcion: "Union perfil de 20 cm Alurack",
      unidad: "und",
      cantidadProyectada: 20,
      precioPromedioInternet: 3962,
      notas: "Solar Hub CTSHCAR260235",
    },
    {
      id: "shared-extra-tornillo-inox-alurack",
      project: "20kW",
      section: "2. ESTRUCTURA DE MONTAJE",
      seccionOperativa: "Techo solar",
      descripcion: "Tornillo inoxidable 8x25 cm Alurack",
      unidad: "und",
      cantidadProyectada: 40,
      precioPromedioInternet: 812,
      notas: "Solar Hub CTSHCAR260235",
    },
    {
      id: "shared-extra-mc4-pares",
      project: "20kW",
      section: "3. CIRCUITO DC",
      seccionOperativa: "Techo solar",
      descripcion: "Pares MC4 Staubli adicionales (macho+hembra)",
      unidad: "par",
      cantidadProyectada: 18,
      precioPromedioInternet: 10570,
      notas: "Solar Hub: 30 pares totales; 12 asignados a 8kW/20kW base",
    },
    {
      id: "shared-defa-ajuste-conduleta",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Ajuste neto devolucion/recompra conduleta DEFA",
      unidad: "global",
      cantidadProyectada: 1,
      precioPromedioInternet: 4000,
      notas: "Devolucion EMT 1 T + recompra EMT 1 LR — +$4.000 a cuenta DEFA",
    },
  ],
  invoices: [
    // ========== SOLAR HUB CTSHCAR260235 — $39.002.846 ==========
    {
      id: "inv-shc-mod-8kw",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-1",
      project: "8kW",
      qty: 12,
      unitPrice: 409000,
      total: 4908000,
    },
    {
      id: "inv-shc-mod-20kw",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-1",
      project: "20kW",
      qty: 39,
      unitPrice: 409000,
      total: 15951000,
    },
    {
      id: "inv-shc-inv-8kw",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-2",
      project: "8kW",
      qty: 1,
      unitPrice: 2906600,
      total: 2906600,
    },
    {
      id: "inv-shc-inv-20kw",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-2",
      project: "20kW",
      qty: 2,
      unitPrice: 3213000,
      total: 6426000,
    },
    {
      id: "inv-shc-dongle",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "shared-extra-dongle-huawei",
      project: "20kW",
      qty: 2,
      unitPrice: 249900,
      total: 499800,
    },
    {
      id: "inv-shc-ground",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-7",
      project: "20kW",
      qty: 4,
      unitPrice: 4088,
      total: 16352,
    },
    {
      id: "inv-shc-eclamp-8",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-5",
      project: "8kW",
      qty: 8,
      unitPrice: 4661,
      total: 37288,
    },
    {
      id: "inv-shc-eclamp-20",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-5",
      project: "20kW",
      qty: 8,
      unitPrice: 4661,
      total: 37288,
    },
    {
      id: "inv-shc-mclamp-8",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-6",
      project: "8kW",
      qty: 20,
      unitPrice: 4810,
      total: 96200,
    },
    {
      id: "inv-shc-mclamp-20",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-6",
      project: "20kW",
      qty: 74,
      unitPrice: 4810,
      total: 355940,
    },
    {
      id: "inv-shc-lhanger-8",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-4",
      project: "8kW",
      itemDescription: "L-Hanger + tornillo fijacion 125/70",
      qty: 22,
      unitPrice: 31069,
      total: 683518,
    },
    {
      id: "inv-shc-lhanger-20",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-4",
      project: "20kW",
      itemDescription: "L-Hanger + tornillo fijacion 125/70",
      qty: 66,
      unitPrice: 31069,
      total: 2050554,
    },
    {
      id: "inv-shc-mrail-8",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-3",
      project: "8kW",
      qty: 60,
      unitPrice: 25837,
      total: 1550220,
    },
    {
      id: "inv-shc-mrail-20",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-3",
      project: "20kW",
      qty: 63.8,
      unitPrice: 25837,
      total: 1648401,
    },
    {
      id: "inv-shc-union-perfil",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "shared-extra-union-perfil-alurack",
      project: "20kW",
      qty: 20,
      unitPrice: 3962,
      total: 79240,
    },
    {
      id: "inv-shc-tornillo-inox",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "shared-extra-tornillo-inox-alurack",
      project: "20kW",
      qty: 40,
      unitPrice: 812,
      total: 32480,
    },
    {
      id: "inv-shc-mc4-8",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-10",
      project: "8kW",
      qty: 4,
      unitPrice: 10570,
      total: 42280,
    },
    {
      id: "inv-shc-mc4-20",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-10",
      project: "20kW",
      qty: 8,
      unitPrice: 10570,
      total: 84560,
    },
    {
      id: "inv-shc-mc4-extra",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "shared-extra-mc4-pares",
      project: "20kW",
      qty: 18,
      unitPrice: 10570,
      total: 190260,
    },

    // ========== DEFA PAEA15795 — $2.954.424,77 + $4.000 ==========
    {
      id: "inv-defa-v3-union-imc",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-union-imc-34",
      project: "8kW",
      qty: 4,
      unitPrice: 944,
      total: 3776,
    },
    {
      id: "inv-defa-v3-curva-emt",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-curva-emt-1",
      project: "20kW",
      qty: 5,
      unitPrice: 1981,
      total: 9905,
    },
    {
      id: "inv-defa-v3-curva-imc",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-curva-imc-34",
      project: "8kW",
      qty: 6,
      unitPrice: 3255,
      total: 19530,
    },
    {
      id: "inv-defa-v3-term-emt",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-terminal-emt-1",
      project: "20kW",
      qty: 4,
      unitPrice: 1261,
      total: 5044,
    },
    {
      id: "inv-defa-v3-union-emt",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-union-emt-1",
      project: "20kW",
      qty: 6,
      unitPrice: 947,
      total: 5682,
    },
    {
      id: "inv-defa-v3-emt-8",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "8kW-19",
      project: "8kW",
      qty: 11,
      unitPrice: 7151,
      total: 78661,
    },
    {
      id: "inv-defa-v3-emt-20",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "20kW-21",
      project: "20kW",
      qty: 7,
      unitPrice: 7151,
      total: 50057,
    },
    {
      id: "inv-defa-v3-imc",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "8kW-21",
      project: "8kW",
      qty: 30,
      unitPrice: 9220,
      total: 276600,
    },
    {
      id: "inv-defa-v3-boquilla",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-boquilla-34",
      project: "8kW",
      qty: 4,
      unitPrice: 758,
      total: 3032,
    },
    {
      id: "inv-defa-v3-cinta-n",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-cinta-negra",
      project: "8kW",
      qty: 1,
      unitPrice: 2269,
      total: 2269,
    },
    {
      id: "inv-defa-v3-cinta-b",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-cinta-blanca",
      project: "8kW",
      qty: 1,
      unitPrice: 2297,
      total: 2297,
    },
    {
      id: "inv-defa-v3-cinta-r",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-cinta-roja",
      project: "20kW",
      qty: 1,
      unitPrice: 4790,
      total: 4790,
    },
    {
      id: "inv-defa-v3-cinta-v",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-cinta-verde",
      project: "20kW",
      qty: 1,
      unitPrice: 4790,
      total: 4790,
    },
    {
      id: "inv-defa-v3-conduleta",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-conduleta-emt1",
      project: "20kW",
      qty: 2,
      unitPrice: 11319,
      total: 22638,
    },
    {
      id: "inv-defa-v3-awg6-negro",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "8kW-14",
      project: "8kW",
      itemDescription: "Cable cobre #6 negro Centelsa",
      qty: 120,
      unitPrice: 8800,
      total: 1056000,
    },
    {
      id: "inv-defa-v3-rawelt",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-caja-rawelt",
      project: "20kW",
      qty: 4,
      unitPrice: 16376,
      total: 65504,
    },
    {
      id: "inv-defa-v3-grapa",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-grapa-emt1",
      project: "20kW",
      qty: 12,
      unitPrice: 236,
      total: 2832,
    },
    {
      id: "inv-defa-v3-awg6-verde",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "20kW-18",
      project: "20kW",
      itemDescription: "Cable cobre #6 verde Procables",
      qty: 60,
      unitPrice: 8670,
      total: 520200,
    },
    {
      id: "inv-defa-v3-awg8-verde",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "8kW-15",
      project: "8kW",
      itemDescription: "Cable cobre #8 verde Procables",
      qty: 60,
      unitPrice: 5750,
      total: 345000,
    },
    {
      id: "inv-defa-v3-tensor",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-tensor-antifraude",
      project: "20kW",
      qty: 2,
      unitPrice: 2052,
      total: 4104,
    },
    {
      id: "inv-defa-v3-ajuste-conduleta",
      date: "2026-07-09",
      number: "PAEA15807",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1jkqv28YnA8j8sZfMZSmMmeYtDFzyZwXq/view?usp=sharing",
      itemId: "shared-defa-ajuste-conduleta",
      project: "20kW",
      qty: 1,
      unitPrice: 4000,
      total: 4000,
      itemDescription: "Ajuste neto devolucion/recompra conduleta (+$4.000)",
    },

    // ========== Soluciones Electricas N3598 — $400.000 ==========
    {
      id: "inv-sep-v3-caja8",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "20kW-extra-caja-8p",
      project: "20kW",
      qty: 1,
      unitPrice: 35000,
      total: 35000,
    },
    {
      id: "inv-sep-v3-caja6",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "8kW-extra-caja-6p",
      project: "8kW",
      qty: 1,
      unitPrice: 26000,
      total: 26000,
    },
    {
      id: "inv-sep-v3-breaker",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "20kW-16",
      project: "20kW",
      qty: 2,
      unitPrice: 50000,
      total: 100000,
    },
    {
      id: "inv-sep-v3-breaker-x",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "20kW-extra-breaker-63A",
      project: "20kW",
      qty: 1,
      unitPrice: 50000,
      total: 50000,
    },
    {
      id: "inv-sep-v3-amarras",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "shared-extra-amarras",
      project: "8kW",
      qty: 1,
      unitPrice: 11000,
      total: 11000,
    },
    {
      id: "inv-sep-v3-totalizador",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "20kW-extra-totalizador-100A",
      project: "20kW",
      qty: 1,
      unitPrice: 160000,
      total: 160000,
    },
    {
      id: "inv-sep-v3-barra",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "shared-extra-terminal-barra",
      project: "20kW",
      qty: 4,
      unitPrice: 3000,
      total: 12000,
    },
    {
      id: "inv-sep-v3-pin",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "shared-extra-terminal-pin",
      project: "20kW",
      qty: 12,
      unitPrice: 500,
      total: 6000,
    },

    // ========== Casa Dielectrica — $75.000 ==========
    {
      id: "inv-cd-v3-caja12",
      date: "2026-07-10",
      number: "FEA5-32889",
      supplier: "Casa Dielectrica (Maria Ximena Navia)",
      location: "CR 23 17-10, Pasto",
      fileLink: "https://drive.google.com/file/d/1f9c-aZ18KPgx8eE6PR0wwxaWqKO6Sic5/view?usp=sharing",
      itemId: "20kW-extra-caja-12p",
      project: "20kW",
      qty: 2,
      unitPrice: 37500,
      total: 75000,
    },

    // ========== DEFA PAEA15948 — 14-jul-2026 — $2.934.370,62 (con IVA) ==========
    // Lineas registradas a valor unitario / subtotal sin IVA (igual que PAEA15795).
    {
      id: "inv-defa-v5-awg2",
      date: "2026-07-14",
      number: "PAEA15948",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1PKtGs2v05OqMwyidtyLTe6-2Bdg12loq/view?usp=sharing",
      itemId: "20kW-17",
      project: "20kW",
      itemDescription: "MT. Cable cobre aislado #2 Centelsa CE-0502",
      qty: 110,
      unitPrice: 21725,
      total: 2389750,
    },
    {
      id: "inv-defa-v5-conector-coraza",
      date: "2026-07-14",
      number: "PAEA15948",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1PKtGs2v05OqMwyidtyLTe6-2Bdg12loq/view?usp=sharing",
      itemId: "shared-extra-conector-coraza-1",
      project: "20kW",
      itemDescription: "Conector recto 1\" coraza",
      qty: 17,
      unitPrice: 4418.98,
      total: 75122.66,
    },
    {
      id: "inv-defa-v5-grapa-34",
      date: "2026-07-14",
      number: "PAEA15948",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1PKtGs2v05OqMwyidtyLTe6-2Bdg12loq/view?usp=sharing",
      itemId: "shared-extra-grapa-imc-34",
      project: "20kW",
      itemDescription: "Grapa doble oreja 3/4\" Galv IMC/EMT",
      qty: 5,
      unitPrice: 197,
      total: 985,
    },

    // ========== INELDEC C-1-10482 — 16-jul-2026 — $3.933.000 (con IVA) ==========
    // Cotizacion iSiigo; lineas a Vr. Unitario / Vr. Bruto sin IVA.
    {
      id: "inv-ineldec-v6-breaker-20kw",
      date: "2026-07-16",
      number: "C-1-10482",
      supplier: "INELDEC ENERGY SAS",
      location: "Villa del Rosario / entrega ciudad principal",
      fileLink: "../compras/PDF/C-1-10482 LG LUIS CARLOS TABARES MILLAN.pdf",
      itemId: "20kW-11",
      project: "20kW",
      itemDescription: "Breaker riel 2x20A 2kA 1000V DC Suntree",
      qty: 4,
      unitPrice: 149579.83,
      total: 598319.32,
    },
    {
      id: "inv-ineldec-v6-breaker-8kw",
      date: "2026-07-16",
      number: "C-1-10482",
      supplier: "INELDEC ENERGY SAS",
      location: "Villa del Rosario / entrega ciudad principal",
      fileLink: "../compras/PDF/C-1-10482 LG LUIS CARLOS TABARES MILLAN.pdf",
      itemId: "8kW-extra-seccionador-dc-20A",
      project: "8kW",
      itemDescription: "Breaker riel 2x20A 2kA 1000V DC Suntree",
      qty: 2,
      unitPrice: 149579.83,
      total: 299159.66,
    },
    {
      id: "inv-ineldec-v6-cable-negro-8",
      date: "2026-07-16",
      number: "C-1-10482",
      supplier: "INELDEC ENERGY SAS",
      location: "Villa del Rosario / entrega ciudad principal",
      fileLink: "../compras/PDF/C-1-10482 LG LUIS CARLOS TABARES MILLAN.pdf",
      itemId: "8kW-8",
      project: "8kW",
      itemDescription: "Cable PV 6mm2 negro Leader",
      qty: 36,
      unitPrice: 6302.52,
      total: 226890.72,
    },
    {
      id: "inv-ineldec-v6-cable-rojo-8",
      date: "2026-07-16",
      number: "C-1-10482",
      supplier: "INELDEC ENERGY SAS",
      location: "Villa del Rosario / entrega ciudad principal",
      fileLink: "../compras/PDF/C-1-10482 LG LUIS CARLOS TABARES MILLAN.pdf",
      itemId: "8kW-8",
      project: "8kW",
      itemDescription: "Cable PV 6mm2 rojo Leader",
      qty: 36,
      unitPrice: 6302.52,
      total: 226890.72,
    },
    {
      id: "inv-ineldec-v6-cable-negro-20",
      date: "2026-07-16",
      number: "C-1-10482",
      supplier: "INELDEC ENERGY SAS",
      location: "Villa del Rosario / entrega ciudad principal",
      fileLink: "../compras/PDF/C-1-10482 LG LUIS CARLOS TABARES MILLAN.pdf",
      itemId: "20kW-8",
      project: "20kW",
      itemDescription: "Cable PV 6mm2 negro Leader",
      qty: 79,
      unitPrice: 6302.52,
      total: 497899.08,
    },
    {
      id: "inv-ineldec-v6-cable-rojo-20",
      date: "2026-07-16",
      number: "C-1-10482",
      supplier: "INELDEC ENERGY SAS",
      location: "Villa del Rosario / entrega ciudad principal",
      fileLink: "../compras/PDF/C-1-10482 LG LUIS CARLOS TABARES MILLAN.pdf",
      itemId: "20kW-8",
      project: "20kW",
      itemDescription: "Cable PV 6mm2 rojo Leader",
      qty: 79,
      unitPrice: 6302.52,
      total: 497899.08,
    },
    {
      id: "inv-ineldec-v6-dps-dc-8",
      date: "2026-07-16",
      number: "C-1-10482",
      supplier: "INELDEC ENERGY SAS",
      location: "Villa del Rosario / entrega ciudad principal",
      fileLink: "../compras/PDF/C-1-10482 LG LUIS CARLOS TABARES MILLAN.pdf",
      itemId: "8kW-12",
      project: "8kW",
      itemDescription: "DPS Tipo II 1000V DC 3 polos 20-40kA Suntree",
      qty: 1,
      unitPrice: 218487.39,
      total: 218487.39,
    },
    {
      id: "inv-ineldec-v6-dps-dc-20",
      date: "2026-07-16",
      number: "C-1-10482",
      supplier: "INELDEC ENERGY SAS",
      location: "Villa del Rosario / entrega ciudad principal",
      fileLink: "../compras/PDF/C-1-10482 LG LUIS CARLOS TABARES MILLAN.pdf",
      itemId: "20kW-13",
      project: "20kW",
      itemDescription: "DPS Tipo II 1000V DC 3 polos 20-40kA Suntree",
      qty: 2,
      unitPrice: 218487.39,
      total: 436974.78,
    },
    {
      id: "inv-ineldec-v6-dps-ac-8",
      date: "2026-07-16",
      number: "C-1-10482",
      supplier: "INELDEC ENERGY SAS",
      location: "Villa del Rosario / entrega ciudad principal",
      fileLink: "../compras/PDF/C-1-10482 LG LUIS CARLOS TABARES MILLAN.pdf",
      itemId: "8kW-17",
      project: "8kW",
      itemDescription: "DPS Tipo II 275V AC 2 polos 20-40kA Suntree",
      qty: 1,
      unitPrice: 151260.50,
      total: 151260.50,
    },
    {
      id: "inv-ineldec-v6-dps-ac-20",
      date: "2026-07-16",
      number: "C-1-10482",
      supplier: "INELDEC ENERGY SAS",
      location: "Villa del Rosario / entrega ciudad principal",
      fileLink: "../compras/PDF/C-1-10482 LG LUIS CARLOS TABARES MILLAN.pdf",
      itemId: "20kW-19",
      project: "20kW",
      itemDescription: "DPS Tipo II 275V AC 2 polos 20-40kA Suntree",
      qty: 1,
      unitPrice: 151260.50,
      total: 151260.50,
    },

    // ========== Casa Electrica FE1-277774 — 14-jul-2026 — $5.200 (Gustavo A.) ==========
    {
      id: "inv-ce-v9-grapa-tensora",
      date: "2026-07-14",
      number: "FE1-277774",
      supplier: "Casa Electrica (Dario Navia Cujar)",
      location: "CR 23 17 64, Pasto",
      fileLink: "/pdfs/Factura_Casa_Electrica.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-grapa-tensora-t2",
      project: "20kW",
      itemDescription: "Grapa tensora para acometida T-2",
      qty: 1,
      unitPrice: 5200,
      total: 5200,
    },

    // ========== Casa Electrica FE1-277678 — 14-jul-2026 — $200.400 (Gustavo A.) ==========
    {
      id: "inv-ce-v9-coraza",
      date: "2026-07-14",
      number: "FE1-277678",
      supplier: "Casa Electrica (Dario Navia Cujar)",
      location: "CR 23 17 64, Pasto",
      fileLink: "/pdfs/Factura_Casa_Electrica_277678.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-coraza-1",
      project: "20kW",
      itemDescription: "Coraza metal protegida 1\"",
      qty: 4,
      unitPrice: 10300,
      total: 41200,
    },
    {
      id: "inv-ce-v9-disco",
      date: "2026-07-14",
      number: "FE1-277678",
      supplier: "Casa Electrica (Dario Navia Cujar)",
      location: "CR 23 17 64, Pasto",
      fileLink: "/pdfs/Factura_Casa_Electrica_277678.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-disco-corte-metal",
      project: "20kW",
      qty: 2,
      unitPrice: 2000,
      total: 4000,
    },
    {
      id: "inv-ce-v9-conector-coraza",
      date: "2026-07-14",
      number: "FE1-277678",
      supplier: "Casa Electrica (Dario Navia Cujar)",
      location: "CR 23 17 64, Pasto",
      fileLink: "/pdfs/Factura_Casa_Electrica_277678.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-conector-coraza-1",
      project: "20kW",
      itemDescription: "Conector 1\" EMT a coraza",
      qty: 20,
      unitPrice: 7500,
      total: 150000,
    },
    {
      id: "inv-ce-v9-ancla",
      date: "2026-07-14",
      number: "FE1-277678",
      supplier: "Casa Electrica (Dario Navia Cujar)",
      location: "CR 23 17 64, Pasto",
      fileLink: "/pdfs/Factura_Casa_Electrica_277678.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-ancla-hlc-516",
      project: "20kW",
      qty: 4,
      unitPrice: 500,
      total: 2000,
    },
    {
      id: "inv-ce-v9-broca",
      date: "2026-07-14",
      number: "FE1-277678",
      supplier: "Casa Electrica (Dario Navia Cujar)",
      location: "CR 23 17 64, Pasto",
      fileLink: "/pdfs/Factura_Casa_Electrica_277678.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-broca-muro-516",
      project: "20kW",
      qty: 1,
      unitPrice: 3000,
      total: 3000,
    },
    {
      id: "inv-ce-v9-bolsa",
      date: "2026-07-14",
      number: "FE1-277678",
      supplier: "Casa Electrica (Dario Navia Cujar)",
      location: "CR 23 17 64, Pasto",
      fileLink: "/pdfs/Factura_Casa_Electrica_277678.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-bolsa-manigueta",
      project: "20kW",
      itemDescription: "Bolsa manigueta biodegradable",
      qty: 1,
      unitPrice: 200,
      total: 200,
    },

    // ========== Todo Tornillo FETT 00289611 — 15-jul-2026 — $22.525 (Gustavo A.) ==========
    {
      id: "inv-tt-v9-arandela",
      date: "2026-07-15",
      number: "FETT-00289611",
      supplier: "Ramirez y David SAS (Todo Tornillo)",
      location: "Cra 19 14-21, Pasto",
      fileLink: "/pdfs/Factura_convertida.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-ferreteria-todo-tornillo",
      project: "20kW",
      itemDescription: "Arandela redonda cobre/zinc 1/4\"",
      qty: 25,
      unitPrice: 117,
      total: 2925,
    },
    {
      id: "inv-tt-v9-chazo-ancla",
      date: "2026-07-15",
      number: "FETT-00289611",
      supplier: "Ramirez y David SAS (Todo Tornillo)",
      location: "Cra 19 14-21, Pasto",
      fileLink: "/pdfs/Factura_convertida.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-ferreteria-todo-tornillo",
      project: "20kW",
      itemDescription: "Chazo ancla 5/16 x 2",
      qty: 20,
      unitPrice: 460,
      total: 9200,
    },
    {
      id: "inv-tt-v9-chazo-plastico",
      date: "2026-07-15",
      number: "FETT-00289611",
      supplier: "Ramirez y David SAS (Todo Tornillo)",
      location: "Cra 19 14-21, Pasto",
      fileLink: "/pdfs/Factura_convertida.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-ferreteria-todo-tornillo",
      project: "20kW",
      itemDescription: "Chazo plastico 1/4 ranurado",
      qty: 25,
      unitPrice: 39,
      total: 975,
    },
    {
      id: "inv-tt-v9-flange",
      date: "2026-07-15",
      number: "FETT-00289611",
      supplier: "Ramirez y David SAS (Todo Tornillo)",
      location: "Cra 19 14-21, Pasto",
      fileLink: "/pdfs/Factura_convertida.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-ferreteria-todo-tornillo",
      project: "20kW",
      itemDescription: "Tornillo flange 6 mm",
      qty: 25,
      unitPrice: 60,
      total: 1500,
    },
    {
      id: "inv-tt-v9-drywall",
      date: "2026-07-15",
      number: "FETT-00289611",
      supplier: "Ramirez y David SAS (Todo Tornillo)",
      location: "Cra 19 14-21, Pasto",
      fileLink: "/pdfs/Factura_convertida.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-ferreteria-todo-tornillo",
      project: "20kW",
      itemDescription: "Tornillo drywall 5/8 zincado",
      qty: 25,
      unitPrice: 32,
      total: 800,
    },
    {
      id: "inv-tt-v9-pan",
      date: "2026-07-15",
      number: "FETT-00289611",
      supplier: "Ramirez y David SAS (Todo Tornillo)",
      location: "Cra 19 14-21, Pasto",
      fileLink: "/pdfs/Factura_convertida.pdf",
      purchasedBy: "Gustavo A.",
      itemId: "shared-extra-ferreteria-todo-tornillo",
      project: "20kW",
      itemDescription: "Tornillo pan phillips 6x30",
      qty: 25,
      unitPrice: 285,
      total: 7125,
    },
  ],
};
