/**
 * Compras detectadas en /compras (fotos Julio 2026).
 * Tubo EMT/IMC: se asume barra estandar de 3 m.
 * DEFA PAEA15795: solo pagina 1 fotografiada; faltan items de pagina 2
 * (total factura ~$2.954.425 vs ~$461k visibles en pagina 1).
 */
const COMPRAS_IMPORT = {
  version: "compras-v1",
  notes: [
    "IMG_1790: consignacion Bancolombia $39.002.846 sin desglose de materiales.",
    "IMG_2123: Dist. Electricas AC $249.776 sin desglose de items.",
    "IMG_2130: DEFA PAEA15795 pagina 1/2 — falta fotografiar pagina 2.",
    "IMG_2131: Soluciones Electricas Pasto orden 3598.",
    "IMG_2132: Casa Dielectrica FEA5-32889.",
  ],
  newItems: [
    {
      id: "20kW-extra-totalizador-100A",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Totalizador bifasico 100 A (acometida / tablero principal)",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 160000,
      notas: "Comprado en Soluciones Electricas Pasto (orden 3598)",
    },
    {
      id: "20kW-extra-caja-8p",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Caja de distribucion sobreponer con tapa 8P",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 35000,
      notas: "Soluciones Electricas Pasto",
    },
    {
      id: "8kW-extra-caja-6p",
      project: "8kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Caja de distribucion sobreponer con tapa 6P",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 26000,
      notas: "Soluciones Electricas Pasto",
    },
    {
      id: "20kW-extra-caja-12p",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Caja plastica con tapa 12P (Voltio) para protecciones",
      unidad: "und",
      cantidadProyectada: 2,
      precioPromedioInternet: 37500,
      notas: "Casa Dielectrica FEA5-32889",
    },
    {
      id: "20kW-extra-breaker-63A",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Minibreaker Schneider 2P 63 A (respaldo / salida adicional)",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 50000,
      notas: "Tercera unidad comprada; presupuesto base contempla 2x63A en 20kW-16",
    },
    {
      id: "shared-extra-amarras",
      project: "8kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Paquete de amarras plasticas",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 11000,
      notas: "Uso compartido ambos proyectos — Soluciones Electricas",
    },
    {
      id: "shared-extra-terminal-barra",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Terminal / barra 2 bornes (tierra o neutro)",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 12000,
      notas: "Soluciones Electricas Pasto — lectura parcial del ticket",
    },
    {
      id: "shared-extra-terminal-pin",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Terminal pin hueco + terminal tierra verde",
      unidad: "und",
      cantidadProyectada: 12,
      precioPromedioInternet: 500,
      notas: "Soluciones Electricas Pasto",
    },
    {
      id: "shared-extra-union-imc-34",
      project: "8kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Union galvanizada / IMC 3/4\"",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 944,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-curva-emt-1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Curva EMT 1\"",
      unidad: "und",
      cantidadProyectada: 5,
      precioPromedioInternet: 1981,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-curva-imc-34",
      project: "8kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Curva galvanizada / IMC 3/4\"",
      unidad: "und",
      cantidadProyectada: 6,
      precioPromedioInternet: 3255,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-terminal-emt-1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Terminal EMT 1\" acero",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 1261,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-union-emt-1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Union EMT 1\" acero",
      unidad: "und",
      cantidadProyectada: 6,
      precioPromedioInternet: 947,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-boquilla-34",
      project: "8kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Juego de boquilla y contratuerca 3/4\"",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 758,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-cinta-negra",
      project: "8kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Cinta aislante negra economica x 18 m",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 2269,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-cinta-blanca",
      project: "8kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Cinta aislante blanca",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 2297,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-cinta-roja",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Cinta aislante Temflex roja grande",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 4790,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-pago-bancolombia",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Pago Bancolombia por imputar (equipos/materiales sin desglose)",
      unidad: "global",
      cantidadProyectada: 1,
      precioPromedioInternet: 39002846,
      notas: "Comprobante 209499422 · 25/06 · $39.002.846 · falta asignar a modulos/inversores",
    },
    {
      id: "shared-pago-dist-electricas",
      project: "8kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Compra Dist. Electricas AC (sin desglose de items)",
      unidad: "global",
      cantidadProyectada: 1,
      precioPromedioInternet: 249776,
      notas: "Credibanco 11/07 · CL 22 20B 21 Av Santander · $249.776 · falta factura detallada",
    },
    {
      id: "shared-defa-pagina2-pendiente",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "DEFA PAEA15795 pagina 2 pendiente de registrar (cables u otros)",
      unidad: "global",
      cantidadProyectada: 1,
      precioPromedioInternet: 2021068,
      notas: "Total factura $2.954.425 - items pagina 1 ~$461k - IVA incluido en total. Subtotal faltante aprox $2.021.068 sin IVA. Falta foto pagina 2.",
    },
  ],
  invoices: [
    // --- DEFA PAEA15795 (tubos en ml = barras x 3 m) ---
    {
      id: "inv-defa-emt-8kw",
      date: "2026-07-09",
      number: "PAEA15795-EMT-8kW",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "8kW-19",
      project: "8kW",
      itemDescription: "Tubería EMT 1\"",
      qty: 11,
      unitPrice: 7151,
      total: 78661,
    },
    {
      id: "inv-defa-emt-20kw",
      date: "2026-07-09",
      number: "PAEA15795-EMT-20kW",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "20kW-21",
      project: "20kW",
      itemDescription: "Tubería EMT 1\"",
      qty: 7,
      unitPrice: 7151,
      total: 50057,
    },
    {
      id: "inv-defa-imc-8kw",
      date: "2026-07-09",
      number: "PAEA15795-IMC",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "8kW-21",
      project: "8kW",
      itemDescription: "Tubería IMC 3/4\"",
      qty: 21,
      unitPrice: 13171,
      total: 276591,
    },
    {
      id: "inv-defa-union-imc",
      date: "2026-07-09",
      number: "PAEA15795-ACC-1",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "shared-extra-union-imc-34",
      project: "8kW",
      qty: 4,
      unitPrice: 944,
      total: 3776,
    },
    {
      id: "inv-defa-curva-emt",
      date: "2026-07-09",
      number: "PAEA15795-ACC-2",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "shared-extra-curva-emt-1",
      project: "20kW",
      qty: 5,
      unitPrice: 1981,
      total: 9905,
    },
    {
      id: "inv-defa-curva-imc",
      date: "2026-07-09",
      number: "PAEA15795-ACC-3",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "shared-extra-curva-imc-34",
      project: "8kW",
      qty: 6,
      unitPrice: 3255,
      total: 19530,
    },
    {
      id: "inv-defa-term-emt",
      date: "2026-07-09",
      number: "PAEA15795-ACC-4",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "shared-extra-terminal-emt-1",
      project: "20kW",
      qty: 4,
      unitPrice: 1261,
      total: 5044,
    },
    {
      id: "inv-defa-union-emt",
      date: "2026-07-09",
      number: "PAEA15795-ACC-5",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "shared-extra-union-emt-1",
      project: "20kW",
      qty: 6,
      unitPrice: 947,
      total: 5682,
    },
    {
      id: "inv-defa-boquilla",
      date: "2026-07-09",
      number: "PAEA15795-ACC-6",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "shared-extra-boquilla-34",
      project: "8kW",
      qty: 4,
      unitPrice: 758,
      total: 3032,
    },
    {
      id: "inv-defa-cinta-n",
      date: "2026-07-09",
      number: "PAEA15795-CIN-1",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "shared-extra-cinta-negra",
      project: "8kW",
      qty: 1,
      unitPrice: 2269,
      total: 2269,
    },
    {
      id: "inv-defa-cinta-b",
      date: "2026-07-09",
      number: "PAEA15795-CIN-2",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "shared-extra-cinta-blanca",
      project: "8kW",
      qty: 1,
      unitPrice: 2297,
      total: 2297,
    },
    {
      id: "inv-defa-cinta-r",
      date: "2026-07-09",
      number: "PAEA15795-CIN-3",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "shared-extra-cinta-roja",
      project: "20kW",
      qty: 1,
      unitPrice: 4790,
      total: 4790,
    },
    {
      id: "inv-defa-pagina2",
      date: "2026-07-09",
      number: "PAEA15795-PAG2",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      itemId: "shared-defa-pagina2-pendiente",
      project: "20kW",
      qty: 1,
      unitPrice: 2021068,
      total: 2021068,
      itemDescription: "Pendiente desglose pagina 2",
    },

    // --- Soluciones Electricas Pasto 3598 ---
    {
      id: "inv-sep-caja8",
      date: "2026-07-10",
      number: "SEP-3598-1",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      itemId: "20kW-extra-caja-8p",
      project: "20kW",
      qty: 1,
      unitPrice: 35000,
      total: 35000,
    },
    {
      id: "inv-sep-caja6",
      date: "2026-07-10",
      number: "SEP-3598-2",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      itemId: "8kW-extra-caja-6p",
      project: "8kW",
      qty: 1,
      unitPrice: 26000,
      total: 26000,
    },
    {
      id: "inv-sep-breaker-base",
      date: "2026-07-10",
      number: "SEP-3598-3A",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      itemId: "20kW-16",
      project: "20kW",
      itemDescription: "Interruptor termomagnetico 2P 63 A",
      qty: 2,
      unitPrice: 50000,
      total: 100000,
    },
    {
      id: "inv-sep-breaker-extra",
      date: "2026-07-10",
      number: "SEP-3598-3B",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      itemId: "20kW-extra-breaker-63A",
      project: "20kW",
      qty: 1,
      unitPrice: 50000,
      total: 50000,
    },
    {
      id: "inv-sep-amarras",
      date: "2026-07-10",
      number: "SEP-3598-4",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      itemId: "shared-extra-amarras",
      project: "8kW",
      qty: 1,
      unitPrice: 11000,
      total: 11000,
    },
    {
      id: "inv-sep-totalizador",
      date: "2026-07-10",
      number: "SEP-3598-5",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      itemId: "20kW-extra-totalizador-100A",
      project: "20kW",
      qty: 1,
      unitPrice: 160000,
      total: 160000,
    },
    {
      id: "inv-sep-barra",
      date: "2026-07-10",
      number: "SEP-3598-6",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      itemId: "shared-extra-terminal-barra",
      project: "20kW",
      qty: 1,
      unitPrice: 12000,
      total: 12000,
    },
    {
      id: "inv-sep-pin",
      date: "2026-07-10",
      number: "SEP-3598-7",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      itemId: "shared-extra-terminal-pin",
      project: "20kW",
      qty: 12,
      unitPrice: 500,
      total: 6000,
    },

    // --- Casa Dielectrica ---
    {
      id: "inv-cd-caja12",
      date: "2026-07-10",
      number: "FEA5-32889",
      supplier: "Casa Dielectrica (Maria Ximena Navia)",
      location: "CR 23 17-10, Pasto",
      itemId: "20kW-extra-caja-12p",
      project: "20kW",
      qty: 2,
      unitPrice: 37500,
      total: 75000,
    },

    // --- Sin desglose ---
    {
      id: "inv-bancolombia",
      date: "2024-06-25",
      number: "BANCOLOMBIA-209499422",
      supplier: "Bancolombia (consignacion)",
      location: "Sucursal Sebastian de Belalcazar, Pasto",
      itemId: "shared-pago-bancolombia",
      project: "20kW",
      qty: 1,
      unitPrice: 39002846,
      total: 39002846,
    },
    {
      id: "inv-dist-ac",
      date: "2026-07-11",
      number: "CREDIBANCO-122326",
      supplier: "Distribuciones Electricas AC P",
      location: "CL 22 20B 21 Av Santander, Pasto",
      itemId: "shared-pago-dist-electricas",
      project: "8kW",
      qty: 1,
      unitPrice: 249776,
      total: 249776,
    },
  ],
};
