/**
 * Compras desde /compras/PDF (Julio 2026).
 * DEFA: PAEA15795 + ajuste +$4.000 por devolucion/recompra conduleta.
 * Tubo EMT/IMC: barra estandar de 3 m.
 */
const COMPRAS_IMPORT = {
  version: "compras-v4",
  notes: [
    "PDF Solar Hub CTSHCAR260235: $39.002.846 (51 paneles, inversores, estructura Alurack, MC4, dongle).",
    "PDF DEFA PAEA15795: $2.954.424,77 + $4.000 ajuste conduleta = $2.958.424,77.",
    "PDF Devolucion conduleta PAEA15807: se devolvio EMT 1 T y se compro EMT 1 LR; neto +$4.000 a DEFA.",
    "PDF Soluciones Electricas N3598: $400.000.",
    "PDF Casa Dielectrica FEA5-32889: $75.000 (2 cajas 12P).",
    "Links de archivo: Google Drive (boton Archivo abre el PDF en Drive).",
  ],
  retireItemIds: [
    "shared-pago-bancolombia",
    "shared-defa-pagina2-pendiente",
    "shared-pago-dist-electricas",
  ],
  supersedeInvoiceIds: [
    "inv-defa-emt-8kw",
    "inv-defa-emt-20kw",
    "inv-defa-imc-8kw",
    "inv-defa-union-imc",
    "inv-defa-curva-emt",
    "inv-defa-curva-imc",
    "inv-defa-term-emt",
    "inv-defa-union-emt",
    "inv-defa-boquilla",
    "inv-defa-cinta-n",
    "inv-defa-cinta-b",
    "inv-defa-cinta-r",
    "inv-defa-pagina2",
    "inv-sep-caja8",
    "inv-sep-caja6",
    "inv-sep-breaker-base",
    "inv-sep-breaker-extra",
    "inv-sep-amarras",
    "inv-sep-totalizador",
    "inv-sep-barra",
    "inv-sep-pin",
    "inv-cd-caja12",
    "inv-dist-ac",
    "inv-bancolombia",
  ],
  newItems: [
    {
      id: "20kW-extra-totalizador-100A",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Totalizador bifasico 100 A (acometida / tablero principal)",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 160000,
      notas: "Soluciones Electricas Pasto N3598",
    },
    {
      id: "20kW-extra-caja-8p",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Caja de distribucion sobreponer con tapa 8P",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 35000,
      notas: "Soluciones Electricas Pasto N3598",
    },
    {
      id: "8kW-extra-caja-6p",
      project: "8kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Caja de distribucion sobreponer con tapa 6P",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 26000,
      notas: "Soluciones Electricas Pasto N3598",
    },
    {
      id: "20kW-extra-caja-12p",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Caja plastica con tapa 12P (Voltio) para protecciones",
      unidad: "und",
      cantidadProyectada: 2,
      precioPromedioInternet: 37500,
      notas: "Casa Dielectrica FEA5-32889",
    },
    {
      id: "20kW-extra-breaker-63A",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Minibreaker Schneider 2P 63 A (respaldo / salida adicional)",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 50000,
      notas: "Tercera unidad — Soluciones Electricas N3598",
    },
    {
      id: "shared-extra-amarras",
      project: "8kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Paquete de amarras plasticas",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 11000,
      notas: "Soluciones Electricas N3598",
    },
    {
      id: "shared-extra-terminal-barra",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Terminal / barra 2 bornes (tern x 2 BYT)",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 3000,
      notas: "Soluciones Electricas N3598 — 4 und x $3.000",
    },
    {
      id: "shared-extra-terminal-pin",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Terminal pin hueco #6 verde",
      unidad: "und",
      cantidadProyectada: 12,
      precioPromedioInternet: 500,
      notas: "Soluciones Electricas N3598",
    },
    {
      id: "shared-extra-union-imc-34",
      project: "8kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Union galvanizada / IMC 3/4\"",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 944,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-curva-emt-1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Curva EMT 1\"",
      unidad: "und",
      cantidadProyectada: 5,
      precioPromedioInternet: 1981,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-curva-imc-34",
      project: "8kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Curva galvanizada / IMC 3/4\"",
      unidad: "und",
      cantidadProyectada: 6,
      precioPromedioInternet: 3255,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-terminal-emt-1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Terminal EMT 1\" acero",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 1261,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-union-emt-1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Union EMT 1\" acero",
      unidad: "und",
      cantidadProyectada: 6,
      precioPromedioInternet: 947,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-boquilla-34",
      project: "8kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Juego de boquilla y contratuerca 3/4\"",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 758,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-cinta-negra",
      project: "8kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Cinta aislante negra economica x 18 m",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 2269,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-cinta-blanca",
      project: "8kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Cinta aislante blanca",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 2297,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-cinta-roja",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Cinta aislante Temflex roja grande",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 4790,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-cinta-verde",
      project: "20kW",
      section: "6. VARIOS Y ACCESORIOS",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Cinta aislante Temflex verde grande",
      unidad: "und",
      cantidadProyectada: 1,
      precioPromedioInternet: 4790,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-conduleta-emt1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Conduleta EMT 1\" LR (recompra tras devolucion T)",
      unidad: "und",
      cantidadProyectada: 2,
      precioPromedioInternet: 12826,
      notas: "DEFA PAEA15807 — ajuste neto +$4.000 sobre PAEA15795",
    },
    {
      id: "shared-extra-caja-rawelt",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Caja tipo Rawelt 2400 3 salidas 3/4\"",
      unidad: "und",
      cantidadProyectada: 4,
      precioPromedioInternet: 16376,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-grapa-emt1",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Grapa doble oreja Galv/EMT 1\" C20",
      unidad: "und",
      cantidadProyectada: 12,
      precioPromedioInternet: 236,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-tensor-antifraude",
      project: "20kW",
      section: "4. CIRCUITO AC",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Tensor antifraude monofasico",
      unidad: "und",
      cantidadProyectada: 2,
      precioPromedioInternet: 2052,
      notas: "DEFA PAEA15795",
    },
    {
      id: "shared-extra-dongle-huawei",
      project: "20kW",
      section: "1. GENERACIÓN FOTOVOLTAICA",
      seccionOperativa: "Cuarto tecnico",
      descripcion: "Dongle Huawei SDONGLEA-05 (02312QMV)",
      unidad: "und",
      cantidadProyectada: 2,
      precioPromedioInternet: 249900,
      notas: "Solar Hub CTSHCAR260235",
    },
    {
      id: "shared-extra-union-perfil-alurack",
      project: "20kW",
      section: "2. ESTRUCTURA DE MONTAJE",
      seccionOperativa: "Techo solar",
      descripcion: "Union perfil de 20 cm Alurack",
      unidad: "und",
      cantidadProyectada: 20,
      precioPromedioInternet: 3962,
      notas: "Solar Hub CTSHCAR260235",
    },
    {
      id: "shared-extra-tornillo-inox-alurack",
      project: "20kW",
      section: "2. ESTRUCTURA DE MONTAJE",
      seccionOperativa: "Techo solar",
      descripcion: "Tornillo inoxidable 8x25 cm Alurack",
      unidad: "und",
      cantidadProyectada: 40,
      precioPromedioInternet: 812,
      notas: "Solar Hub CTSHCAR260235",
    },
    {
      id: "shared-extra-mc4-pares",
      project: "20kW",
      section: "3. CIRCUITO DC",
      seccionOperativa: "Techo solar",
      descripcion: "Pares MC4 Staubli adicionales (macho+hembra)",
      unidad: "par",
      cantidadProyectada: 18,
      precioPromedioInternet: 10570,
      notas: "Solar Hub: 30 pares totales; 12 asignados a 8kW/20kW base",
    },
    {
      id: "shared-defa-ajuste-conduleta",
      project: "20kW",
      section: "5. CANALIZACIONES",
      seccionOperativa: "Conexion acometida principal",
      descripcion: "Ajuste neto devolucion/recompra conduleta DEFA",
      unidad: "global",
      cantidadProyectada: 1,
      precioPromedioInternet: 4000,
      notas: "Devolucion EMT 1 T + recompra EMT 1 LR — +$4.000 a cuenta DEFA",
    },
  ],
  invoices: [
    // ========== SOLAR HUB CTSHCAR260235 — $39.002.846 ==========
    {
      id: "inv-shc-mod-8kw",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-1",
      project: "8kW",
      qty: 12,
      unitPrice: 409000,
      total: 4908000,
    },
    {
      id: "inv-shc-mod-20kw",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-1",
      project: "20kW",
      qty: 39,
      unitPrice: 409000,
      total: 15951000,
    },
    {
      id: "inv-shc-inv-8kw",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-2",
      project: "8kW",
      qty: 1,
      unitPrice: 2906600,
      total: 2906600,
    },
    {
      id: "inv-shc-inv-20kw",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-2",
      project: "20kW",
      qty: 2,
      unitPrice: 3213000,
      total: 6426000,
    },
    {
      id: "inv-shc-dongle",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "shared-extra-dongle-huawei",
      project: "20kW",
      qty: 2,
      unitPrice: 249900,
      total: 499800,
    },
    {
      id: "inv-shc-ground",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-7",
      project: "20kW",
      qty: 4,
      unitPrice: 4088,
      total: 16352,
    },
    {
      id: "inv-shc-eclamp-8",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-5",
      project: "8kW",
      qty: 8,
      unitPrice: 4661,
      total: 37288,
    },
    {
      id: "inv-shc-eclamp-20",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-5",
      project: "20kW",
      qty: 8,
      unitPrice: 4661,
      total: 37288,
    },
    {
      id: "inv-shc-mclamp-8",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-6",
      project: "8kW",
      qty: 20,
      unitPrice: 4810,
      total: 96200,
    },
    {
      id: "inv-shc-mclamp-20",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-6",
      project: "20kW",
      qty: 74,
      unitPrice: 4810,
      total: 355940,
    },
    {
      id: "inv-shc-lhanger-8",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-4",
      project: "8kW",
      itemDescription: "L-Hanger + tornillo fijacion 125/70",
      qty: 22,
      unitPrice: 31069,
      total: 683518,
    },
    {
      id: "inv-shc-lhanger-20",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-4",
      project: "20kW",
      itemDescription: "L-Hanger + tornillo fijacion 125/70",
      qty: 66,
      unitPrice: 31069,
      total: 2050554,
    },
    {
      id: "inv-shc-mrail-8",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-3",
      project: "8kW",
      qty: 60,
      unitPrice: 25837,
      total: 1550220,
    },
    {
      id: "inv-shc-mrail-20",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-3",
      project: "20kW",
      qty: 63.8,
      unitPrice: 25837,
      total: 1648401,
    },
    {
      id: "inv-shc-union-perfil",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "shared-extra-union-perfil-alurack",
      project: "20kW",
      qty: 20,
      unitPrice: 3962,
      total: 79240,
    },
    {
      id: "inv-shc-tornillo-inox",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "shared-extra-tornillo-inox-alurack",
      project: "20kW",
      qty: 40,
      unitPrice: 812,
      total: 32480,
    },
    {
      id: "inv-shc-mc4-8",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "8kW-10",
      project: "8kW",
      qty: 4,
      unitPrice: 10570,
      total: 42280,
    },
    {
      id: "inv-shc-mc4-20",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "20kW-10",
      project: "20kW",
      qty: 8,
      unitPrice: 10570,
      total: 84560,
    },
    {
      id: "inv-shc-mc4-extra",
      date: "2026-06-25",
      number: "CTSHCAR260235",
      supplier: "Solar Hub Colombia SAS",
      location: "Medellin / DDP Narino",
      fileLink: "https://drive.google.com/file/d/1qMfd8ECGO22618ysa6eICzEoWR2MQT2d/view?usp=sharing",
      itemId: "shared-extra-mc4-pares",
      project: "20kW",
      qty: 18,
      unitPrice: 10570,
      total: 190260,
    },

    // ========== DEFA PAEA15795 — $2.954.424,77 + $4.000 ==========
    {
      id: "inv-defa-v3-union-imc",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-union-imc-34",
      project: "8kW",
      qty: 4,
      unitPrice: 944,
      total: 3776,
    },
    {
      id: "inv-defa-v3-curva-emt",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-curva-emt-1",
      project: "20kW",
      qty: 5,
      unitPrice: 1981,
      total: 9905,
    },
    {
      id: "inv-defa-v3-curva-imc",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-curva-imc-34",
      project: "8kW",
      qty: 6,
      unitPrice: 3255,
      total: 19530,
    },
    {
      id: "inv-defa-v3-term-emt",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-terminal-emt-1",
      project: "20kW",
      qty: 4,
      unitPrice: 1261,
      total: 5044,
    },
    {
      id: "inv-defa-v3-union-emt",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-union-emt-1",
      project: "20kW",
      qty: 6,
      unitPrice: 947,
      total: 5682,
    },
    {
      id: "inv-defa-v3-emt-8",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "8kW-19",
      project: "8kW",
      qty: 11,
      unitPrice: 7151,
      total: 78661,
    },
    {
      id: "inv-defa-v3-emt-20",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "20kW-21",
      project: "20kW",
      qty: 7,
      unitPrice: 7151,
      total: 50057,
    },
    {
      id: "inv-defa-v3-imc",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "8kW-21",
      project: "8kW",
      qty: 30,
      unitPrice: 9220,
      total: 276600,
    },
    {
      id: "inv-defa-v3-boquilla",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-boquilla-34",
      project: "8kW",
      qty: 4,
      unitPrice: 758,
      total: 3032,
    },
    {
      id: "inv-defa-v3-cinta-n",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-cinta-negra",
      project: "8kW",
      qty: 1,
      unitPrice: 2269,
      total: 2269,
    },
    {
      id: "inv-defa-v3-cinta-b",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-cinta-blanca",
      project: "8kW",
      qty: 1,
      unitPrice: 2297,
      total: 2297,
    },
    {
      id: "inv-defa-v3-cinta-r",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-cinta-roja",
      project: "20kW",
      qty: 1,
      unitPrice: 4790,
      total: 4790,
    },
    {
      id: "inv-defa-v3-cinta-v",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-cinta-verde",
      project: "20kW",
      qty: 1,
      unitPrice: 4790,
      total: 4790,
    },
    {
      id: "inv-defa-v3-conduleta",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-conduleta-emt1",
      project: "20kW",
      qty: 2,
      unitPrice: 11319,
      total: 22638,
    },
    {
      id: "inv-defa-v3-awg6-negro",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "8kW-14",
      project: "8kW",
      itemDescription: "Cable cobre #6 negro Centelsa",
      qty: 120,
      unitPrice: 8800,
      total: 1056000,
    },
    {
      id: "inv-defa-v3-rawelt",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-caja-rawelt",
      project: "20kW",
      qty: 4,
      unitPrice: 16376,
      total: 65504,
    },
    {
      id: "inv-defa-v3-grapa",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-grapa-emt1",
      project: "20kW",
      qty: 12,
      unitPrice: 236,
      total: 2832,
    },
    {
      id: "inv-defa-v3-awg6-verde",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "20kW-18",
      project: "20kW",
      itemDescription: "Cable cobre #6 verde Procables",
      qty: 60,
      unitPrice: 8670,
      total: 520200,
    },
    {
      id: "inv-defa-v3-awg8-verde",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "8kW-15",
      project: "8kW",
      itemDescription: "Cable cobre #8 verde Procables",
      qty: 60,
      unitPrice: 5750,
      total: 345000,
    },
    {
      id: "inv-defa-v3-tensor",
      date: "2026-07-09",
      number: "PAEA15795",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1C90C9ooS0IO-1IebiyksTo1PMYT5X53J/view",
      itemId: "shared-extra-tensor-antifraude",
      project: "20kW",
      qty: 2,
      unitPrice: 2052,
      total: 4104,
    },
    {
      id: "inv-defa-v3-ajuste-conduleta",
      date: "2026-07-09",
      number: "PAEA15807",
      supplier: "GRUPO DEFA Electricos & Ferreteria",
      location: "Pasto",
      fileLink: "https://drive.google.com/file/d/1jkqv28YnA8j8sZfMZSmMmeYtDFzyZwXq/view?usp=sharing",
      itemId: "shared-defa-ajuste-conduleta",
      project: "20kW",
      qty: 1,
      unitPrice: 4000,
      total: 4000,
      itemDescription: "Ajuste neto devolucion/recompra conduleta (+$4.000)",
    },

    // ========== Soluciones Electricas N3598 — $400.000 ==========
    {
      id: "inv-sep-v3-caja8",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "20kW-extra-caja-8p",
      project: "20kW",
      qty: 1,
      unitPrice: 35000,
      total: 35000,
    },
    {
      id: "inv-sep-v3-caja6",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "8kW-extra-caja-6p",
      project: "8kW",
      qty: 1,
      unitPrice: 26000,
      total: 26000,
    },
    {
      id: "inv-sep-v3-breaker",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "20kW-16",
      project: "20kW",
      qty: 2,
      unitPrice: 50000,
      total: 100000,
    },
    {
      id: "inv-sep-v3-breaker-x",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "20kW-extra-breaker-63A",
      project: "20kW",
      qty: 1,
      unitPrice: 50000,
      total: 50000,
    },
    {
      id: "inv-sep-v3-amarras",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "shared-extra-amarras",
      project: "8kW",
      qty: 1,
      unitPrice: 11000,
      total: 11000,
    },
    {
      id: "inv-sep-v3-totalizador",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "20kW-extra-totalizador-100A",
      project: "20kW",
      qty: 1,
      unitPrice: 160000,
      total: 160000,
    },
    {
      id: "inv-sep-v3-barra",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "shared-extra-terminal-barra",
      project: "20kW",
      qty: 4,
      unitPrice: 3000,
      total: 12000,
    },
    {
      id: "inv-sep-v3-pin",
      date: "2026-07-10",
      number: "N3598",
      supplier: "Soluciones Electricas Pasto",
      location: "Cra 22a No. 14-109 Centro, Pasto",
      fileLink: "https://drive.google.com/file/d/1WT0s-kQ8EYK_H_RtFzNnC1E_AmbrT8tn/view?usp=sharing",
      itemId: "shared-extra-terminal-pin",
      project: "20kW",
      qty: 12,
      unitPrice: 500,
      total: 6000,
    },

    // ========== Casa Dielectrica — $75.000 ==========
    {
      id: "inv-cd-v3-caja12",
      date: "2026-07-10",
      number: "FEA5-32889",
      supplier: "Casa Dielectrica (Maria Ximena Navia)",
      location: "CR 23 17-10, Pasto",
      fileLink: "https://drive.google.com/file/d/1f9c-aZ18KPgx8eE6PR0wwxaWqKO6Sic5/view?usp=sharing",
      itemId: "20kW-extra-caja-12p",
      project: "20kW",
      qty: 2,
      unitPrice: 37500,
      total: 75000,
    },
  ],
};
