const SEED_DATA = {
  "items": [
    {
      "id": "8kW-1",
      "project": "8kW",
      "item": 1,
      "section": "1. GENERACIÓN FOTOVOLTAICA",
      "descripcion": "Módulo fotovoltaico LONGi Hi-MO X10 LR7-72HVHF-650M, 650 Wp, monocristalino",
      "unidad": "und",
      "cantidadProyectada": 12,
      "cantidadComprada": 12,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-2",
      "project": "8kW",
      "item": 2,
      "section": "1. GENERACIÓN FOTOVOLTAICA",
      "descripcion": "Inversor Huawei SUN2000-8K-LC0, 8 kW, monofásico, 3 MPPT",
      "unidad": "und",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-3",
      "project": "8kW",
      "item": 3,
      "section": "2. ESTRUCTURA DE MONTAJE ALURACK (12 módulos, 2 filas, coplanar cubierta)",
      "descripcion": "Riel estructural continuo MRAIL, aluminio 6005 T5/6070 T6",
      "unidad": "ml",
      "cantidadProyectada": 60,
      "cantidadComprada": 60,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-4",
      "project": "8kW",
      "item": 4,
      "section": "2. ESTRUCTURA DE MONTAJE ALURACK (12 módulos, 2 filas, coplanar cubierta)",
      "descripcion": "Soporte L-Hanger + tornillo de fijación 125/70 sobre cresta",
      "unidad": "und",
      "cantidadProyectada": 100,
      "cantidadComprada": 100,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-5",
      "project": "8kW",
      "item": 5,
      "section": "2. ESTRUCTURA DE MONTAJE ALURACK (12 módulos, 2 filas, coplanar cubierta)",
      "descripcion": "ECLAMP 30 mm (fijación extremos de módulo)",
      "unidad": "und",
      "cantidadProyectada": 8,
      "cantidadComprada": 8,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-6",
      "project": "8kW",
      "item": 6,
      "section": "2. ESTRUCTURA DE MONTAJE ALURACK (12 módulos, 2 filas, coplanar cubierta)",
      "descripcion": "MCLAMP 30 mm (fijación intermedia de módulo)",
      "unidad": "und",
      "cantidadProyectada": 20,
      "cantidadComprada": 20,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-7",
      "project": "8kW",
      "item": 7,
      "section": "2. ESTRUCTURA DE MONTAJE ALURACK (12 módulos, 2 filas, coplanar cubierta)",
      "descripcion": "GROUND CLAMP (puesta a tierra de estructura)",
      "unidad": "und",
      "cantidadProyectada": 2,
      "cantidadComprada": 2,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-8",
      "project": "8kW",
      "item": 8,
      "section": "3. CIRCUITO DC (2 cadenas de 6 módulos)",
      "descripcion": "Cable solar H1Z2Z2-K (PV1-F) 6 mm² Cu, 1500 Vdc, rojo/negro",
      "unidad": "ml",
      "cantidadProyectada": 72,
      "cantidadComprada": 72,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-9",
      "project": "8kW",
      "item": 9,
      "section": "3. CIRCUITO DC (2 cadenas de 6 módulos)",
      "descripcion": "Conductor de puesta a tierra de equipos (EGC) #8 AWG Cu THHN",
      "unidad": "ml",
      "cantidadProyectada": 33,
      "cantidadComprada": 33,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-10",
      "project": "8kW",
      "item": 10,
      "section": "3. CIRCUITO DC (2 cadenas de 6 módulos)",
      "descripcion": "Conector MC4 (par macho/hembra)",
      "unidad": "und",
      "cantidadProyectada": 4,
      "cantidadComprada": 4,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-11",
      "project": "8kW",
      "item": 11,
      "section": "3. CIRCUITO DC (2 cadenas de 6 módulos)",
      "descripcion": "Tablero de protecciones DC, IP65, 1000 Vdc, metálico/poliéster",
      "unidad": "und",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-12",
      "project": "8kW",
      "item": 12,
      "section": "3. CIRCUITO DC (2 cadenas de 6 módulos)",
      "descripcion": "DPS DC Tipo II, 2 polos (+/–), Ucpv ≥ 600 Vdc",
      "unidad": "und",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-13",
      "project": "8kW",
      "item": 13,
      "section": "3. CIRCUITO DC (2 cadenas de 6 módulos)",
      "descripcion": "Fusible/portafusible gPV 25 A (respaldo opcional, sectorización)",
      "unidad": "und",
      "cantidadProyectada": 2,
      "cantidadComprada": 2,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-14",
      "project": "8kW",
      "item": 14,
      "section": "4. CIRCUITO AC",
      "descripcion": "Conductor de fase AWG 6 Cu THWN-2 (L1, L2)",
      "unidad": "ml",
      "cantidadProyectada": 132,
      "cantidadComprada": 132,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-15",
      "project": "8kW",
      "item": 15,
      "section": "4. CIRCUITO AC",
      "descripcion": "Conductor de puesta a tierra (EGC) AWG 8 Cu THHN",
      "unidad": "ml",
      "cantidadProyectada": 66,
      "cantidadComprada": 66,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-16",
      "project": "8kW",
      "item": 16,
      "section": "4. CIRCUITO AC",
      "descripcion": "Interruptor termomagnético 2P - 50 A",
      "unidad": "und",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-17",
      "project": "8kW",
      "item": 17,
      "section": "4. CIRCUITO AC",
      "descripcion": "DPS AC Tipo II, 2P (L1-L2+PE), Uc ≥ 275 V",
      "unidad": "und",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-18",
      "project": "8kW",
      "item": 18,
      "section": "4. CIRCUITO AC",
      "descripcion": "Tablero de protecciones AC, IP65",
      "unidad": "und",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-19",
      "project": "8kW",
      "item": 19,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Tubería EMT 1\" (tramos S3+S4+S5: buitrón–tablero AC–inversor–tablero DC)",
      "unidad": "ml",
      "cantidadProyectada": 11,
      "cantidadComprada": 11,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-20",
      "project": "8kW",
      "item": 20,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Accesorios EMT 1\" (uniones, conectores, curvas, abrazaderas)",
      "unidad": "global",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-21",
      "project": "8kW",
      "item": 21,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Tubería IMC 3/4\" (tramos S6+S7: tablero DC–caja de paso–arreglo, 2 vías)",
      "unidad": "ml",
      "cantidadProyectada": 30,
      "cantidadComprada": 30,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-22",
      "project": "8kW",
      "item": 22,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Accesorios IMC 3/4\" (uniones, conectores, curvas, abrazaderas)",
      "unidad": "global",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-23",
      "project": "8kW",
      "item": 23,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Bandeja portacables metálica (tramo S1, sótano–buitrón, 10 m)",
      "unidad": "ml",
      "cantidadProyectada": 10,
      "cantidadComprada": 10,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-24",
      "project": "8kW",
      "item": 24,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Bridas/abrazaderas resistentes a UV (tramo S2, buitrón vertical, 20 m)",
      "unidad": "global",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-25",
      "project": "8kW",
      "item": 25,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Caja de paso en cubierta (techo)",
      "unidad": "und",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-26",
      "project": "8kW",
      "item": 26,
      "section": "6. VARIOS Y ACCESORIOS",
      "descripcion": "Marquilla/rotulado de circuitos y tableros (NTC 2050 / RETIE)",
      "unidad": "global",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-27",
      "project": "8kW",
      "item": 27,
      "section": "6. VARIOS Y ACCESORIOS",
      "descripcion": "Cinta aislante, amarres plásticos, terminales, prensaestopas",
      "unidad": "global",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "8kW-28",
      "project": "8kW",
      "item": 28,
      "section": "6. VARIOS Y ACCESORIOS",
      "descripcion": "Señalización de seguridad (riesgo eléctrico, DC activo)",
      "unidad": "global",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-1",
      "project": "20kW",
      "item": 1,
      "section": "1. GENERACIÓN FOTOVOLTAICA",
      "descripcion": "Módulo fotovoltaico LONGi Hi-MO X10 LR7-72HVHF-650M, 650 Wp, monocristalino",
      "unidad": "und",
      "cantidadProyectada": 39,
      "cantidadComprada": 39,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-2",
      "project": "20kW",
      "item": 2,
      "section": "1. GENERACIÓN FOTOVOLTAICA",
      "descripcion": "Inversor Huawei SUN2000-10K-LC0, 10 kW, monofásico, 3 MPPT",
      "unidad": "und",
      "cantidadProyectada": 2,
      "cantidadComprada": 2,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-3",
      "project": "20kW",
      "item": 3,
      "section": "2. ESTRUCTURA DE MONTAJE ALURACK (39 módulos, 4 filas, coplanar cubierta)",
      "descripcion": "Riel estructural continuo MRAIL, aluminio 6005 T5/6070 T6",
      "unidad": "ml",
      "cantidadProyectada": 178,
      "cantidadComprada": 178,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-4",
      "project": "20kW",
      "item": 4,
      "section": "2. ESTRUCTURA DE MONTAJE ALURACK (39 módulos, 4 filas, coplanar cubierta)",
      "descripcion": "Soporte L-Hanger + tornillo de fijación 125/70 sobre cresta",
      "unidad": "und",
      "cantidadProyectada": 296,
      "cantidadComprada": 296,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-5",
      "project": "20kW",
      "item": 5,
      "section": "2. ESTRUCTURA DE MONTAJE ALURACK (39 módulos, 4 filas, coplanar cubierta)",
      "descripcion": "ECLAMP 30 mm (fijación extremos de módulo)",
      "unidad": "und",
      "cantidadProyectada": 16,
      "cantidadComprada": 16,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-6",
      "project": "20kW",
      "item": 6,
      "section": "2. ESTRUCTURA DE MONTAJE ALURACK (39 módulos, 4 filas, coplanar cubierta)",
      "descripcion": "MCLAMP 30 mm (fijación intermedia de módulo)",
      "unidad": "und",
      "cantidadProyectada": 70,
      "cantidadComprada": 70,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-7",
      "project": "20kW",
      "item": 7,
      "section": "2. ESTRUCTURA DE MONTAJE ALURACK (39 módulos, 4 filas, coplanar cubierta)",
      "descripcion": "GROUND CLAMP (puesta a tierra de estructura)",
      "unidad": "und",
      "cantidadProyectada": 4,
      "cantidadComprada": 4,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-8",
      "project": "20kW",
      "item": 8,
      "section": "3. CIRCUITO DC (4 cadenas: 2x10 + 1x10 + 1x9 módulos)",
      "descripcion": "Cable solar H1Z2Z2-K (PV1-F) 6 mm² Cu, 1500 Vdc, rojo/negro",
      "unidad": "ml",
      "cantidadProyectada": 176,
      "cantidadComprada": 176,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-9",
      "project": "20kW",
      "item": 9,
      "section": "3. CIRCUITO DC (4 cadenas: 2x10 + 1x10 + 1x9 módulos)",
      "descripcion": "Conductor de puesta a tierra de equipos (EGC) #8 AWG Cu THHN",
      "unidad": "ml",
      "cantidadProyectada": 88,
      "cantidadComprada": 88,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-10",
      "project": "20kW",
      "item": 10,
      "section": "3. CIRCUITO DC (4 cadenas: 2x10 + 1x10 + 1x9 módulos)",
      "descripcion": "Conector MC4 (par macho/hembra)",
      "unidad": "und",
      "cantidadProyectada": 8,
      "cantidadComprada": 8,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-11",
      "project": "20kW",
      "item": 11,
      "section": "3. CIRCUITO DC (4 cadenas: 2x10 + 1x10 + 1x9 módulos)",
      "descripcion": "Interruptor-seccionador DC 2P, 20 A, 1000 Vdc, curva C",
      "unidad": "und",
      "cantidadProyectada": 4,
      "cantidadComprada": 4,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-12",
      "project": "20kW",
      "item": 12,
      "section": "3. CIRCUITO DC (4 cadenas: 2x10 + 1x10 + 1x9 módulos)",
      "descripcion": "Tablero DC SFV, IP65, 1000 Vdc, metálico/poliéster",
      "unidad": "und",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-13",
      "project": "20kW",
      "item": 13,
      "section": "3. CIRCUITO DC (4 cadenas: 2x10 + 1x10 + 1x9 módulos)",
      "descripcion": "DPS DC Tipo II, 2 polos (+/–), Ucpv ≥ 600 Vdc",
      "unidad": "und",
      "cantidadProyectada": 2,
      "cantidadComprada": 2,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-14",
      "project": "20kW",
      "item": 14,
      "section": "4. CIRCUITO AC",
      "descripcion": "Conductor de fase AWG 6 Cu HFFRLS (salida individual por inversor, L/N)",
      "unidad": "ml",
      "cantidadProyectada": 9,
      "cantidadComprada": 9,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-15",
      "project": "20kW",
      "item": 15,
      "section": "4. CIRCUITO AC",
      "descripcion": "Conductor de puesta a tierra AWG 8 Cu THHN (salida individual por inversor)",
      "unidad": "ml",
      "cantidadProyectada": 5,
      "cantidadComprada": 5,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-16",
      "project": "20kW",
      "item": 16,
      "section": "4. CIRCUITO AC",
      "descripcion": "Interruptor termomagnético 2P - 63 A (salida de cada inversor)",
      "unidad": "und",
      "cantidadProyectada": 2,
      "cantidadComprada": 2,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-17",
      "project": "20kW",
      "item": 17,
      "section": "4. CIRCUITO AC",
      "descripcion": "Conductor de fase AWG 2 Cu THHN/THWN-2 (alimentador combinado)",
      "unidad": "ml",
      "cantidadProyectada": 132,
      "cantidadComprada": 132,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-18",
      "project": "20kW",
      "item": 18,
      "section": "4. CIRCUITO AC",
      "descripcion": "Conductor de puesta a tierra AWG 6 Cu THHN (alimentador combinado)",
      "unidad": "ml",
      "cantidadProyectada": 66,
      "cantidadComprada": 66,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-19",
      "project": "20kW",
      "item": 19,
      "section": "4. CIRCUITO AC",
      "descripcion": "DPS AC Tipo II, 2P (L1-L2+PE), Uc ≥ 320 V",
      "unidad": "und",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-20",
      "project": "20kW",
      "item": 20,
      "section": "4. CIRCUITO AC",
      "descripcion": "Tablero AC SFV, IP65",
      "unidad": "und",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-21",
      "project": "20kW",
      "item": 21,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Tubería EMT 1\" (tramo T1: arreglo–Tablero DC SFV, 4 vías x 20 m)",
      "unidad": "ml",
      "cantidadProyectada": 80,
      "cantidadComprada": 80,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-22",
      "project": "20kW",
      "item": 22,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Tubería EMT 1\" (tramo T2: Tablero DC SFV–inversores, 4 vías x 2 m)",
      "unidad": "ml",
      "cantidadProyectada": 8,
      "cantidadComprada": 8,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-23",
      "project": "20kW",
      "item": 23,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Tubería EMT 1\" (tramo T3: inversores–Tablero AC SFV, 2 vías x 2 m)",
      "unidad": "ml",
      "cantidadProyectada": 4,
      "cantidadComprada": 4,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-24",
      "project": "20kW",
      "item": 24,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Accesorios EMT 1\" (uniones, conectores, curvas, abrazaderas)",
      "unidad": "global",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-25",
      "project": "20kW",
      "item": 25,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Entubado puntual EMT 1\" en transiciones del alimentador combinado (T4)",
      "unidad": "ml",
      "cantidadProyectada": 6,
      "cantidadComprada": 6,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-26",
      "project": "20kW",
      "item": 26,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Bandeja portacables + soporte en buitrón vertical (tramo T4, 60 m)",
      "unidad": "global",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-27",
      "project": "20kW",
      "item": 27,
      "section": "5. CANALIZACIONES (EMT 1\" — actualizado, diseño original 3/4\")",
      "descripcion": "Caja de paso en cubierta (techo)",
      "unidad": "und",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-28",
      "project": "20kW",
      "item": 28,
      "section": "6. VARIOS Y ACCESORIOS",
      "descripcion": "Marquilla/rotulado de circuitos y tableros (NTC 2050 / RETIE)",
      "unidad": "global",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-29",
      "project": "20kW",
      "item": 29,
      "section": "6. VARIOS Y ACCESORIOS",
      "descripcion": "Cinta aislante, amarres plásticos, terminales, prensaestopas",
      "unidad": "global",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    },
    {
      "id": "20kW-30",
      "project": "20kW",
      "item": 30,
      "section": "6. VARIOS Y ACCESORIOS",
      "descripcion": "Señalización de seguridad (riesgo eléctrico, DC activo)",
      "unidad": "global",
      "cantidadProyectada": 1,
      "cantidadComprada": 1,
      "precioUnitario": 0,
      "notas": ""
    }
  ],
  "aiu": [
    {
      "name": "Mano de obra e instalación",
      "porcentaje": 18
    },
    {
      "name": "Transporte y logística",
      "porcentaje": 4
    },
    {
      "name": "Administración",
      "porcentaje": 6
    },
    {
      "name": "Imprevistos",
      "porcentaje": 5
    },
    {
      "name": "Utilidad",
      "porcentaje": 8
    },
    {
      "name": "Trámites y estudio de conexión ante el operador de red (CEDENAR)",
      "porcentaje": 2
    }
  ]
};
